version: '3.7'

services:
  exporter:
    build: .
    ports:
      - "9000:9000"
    restart: always
    environment:
      API_URL: "http://65.109.136.105:26657"
      LISTEN_IP: "0.0.0.0:9000"

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus.yml:/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always

volumes:
  prometheus: {}